name = "notion-telegram-webhook"
main = "src/index.ts"
compatibility_date = "2026-02-19"
account_id = "a562983dfe7675bfebfb2d980bc21182"

[vars]
GROUP_CHAT_ID = "-1002374110518"
GROUP_THREAD_ID = "10427"
